// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6KTeE7NzCcOyIdrSXdJa8DsNJpzMTKMw',
    appId: '1:1067039429856:web:b0b3180da25d88b66c2c85',
    messagingSenderId: '1067039429856',
    projectId: 'todolist1-f8f20',
    authDomain: 'todolist1-f8f20.firebaseapp.com',
    storageBucket: 'todolist1-f8f20.appspot.com',
    measurementId: 'G-9KNHR73KTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqSsMOIG7ws2voT-EzKTx6pi48eCJYNSY',
    appId: '1:1067039429856:android:6fd44df2849ee4f26c2c85',
    messagingSenderId: '1067039429856',
    projectId: 'todolist1-f8f20',
    storageBucket: 'todolist1-f8f20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0tRq5zVoF5gU9rWxHjam2zUdHU5JKM2c',
    appId: '1:1067039429856:ios:0be9106dadb86d456c2c85',
    messagingSenderId: '1067039429856',
    projectId: 'todolist1-f8f20',
    storageBucket: 'todolist1-f8f20.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0tRq5zVoF5gU9rWxHjam2zUdHU5JKM2c',
    appId: '1:1067039429856:ios:9dbeddd719dff6866c2c85',
    messagingSenderId: '1067039429856',
    projectId: 'todolist1-f8f20',
    storageBucket: 'todolist1-f8f20.appspot.com',
    iosBundleId: 'com.example.todoList.RunnerTests',
  );
}
